# Generated by Django 4.1.2 on 2022-10-14 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default=None, max_length=12)),
                ('customer_name', models.CharField(default=None, max_length=50)),
                ('shop_name', models.CharField(max_length=1000)),
                ('purchase_item', models.CharField(max_length=1000)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('item_price', models.IntegerField()),
                ('purchase_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=1000)),
                ('shop_id', models.IntegerField()),
                ('customer_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='shop_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='owner', max_length=5)),
                ('phone', models.CharField(default=None, max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('shop_name', models.CharField(max_length=1000)),
                ('shop_id', models.CharField(default=True, max_length=50)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='customer', max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('customer_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
