# Generated by Django 4.0.8 on 2022-10-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_history',
            name='duedate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customer_history',
            name='msg',
            field=models.BooleanField(default=False),
        ),
    ]
