# Generated by Django 4.0.8 on 2022-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_history_duedate_customer_history_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_history',
            name='shop_id',
            field=models.IntegerField(default=None),
        ),
    ]
